service:
  name: product-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  environment:
    PRODUCTS_TABLE_NAME: ${self:custom.ProductsTable.name}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    PRODUCTS_BUCKET_NAME: ${self:custom.ProductsBucket.name}
  iamRoleStatements:
    - ${file(iam/ProductsTableIAM.yml):ProductsTableIAM}
    - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
    - ${file(iam/ProductsBucketIAM.yml):ProductsBucketIAM}

resources:
  Resources:
    ProductsTable: ${file(resources/ProductsTable.yml):ProductsTable}
    ProductsBucket: ${file(resources/ProductsBucket.yml):ProductsBucket}
    ProductsBucketPolicy: ${file(resources/ProductsBucket.yml):ProductsBucketPolicy}

functions:
  createProduct:
    handler: src/handlers/createProduct.handler
    events:
      - http:
          method: POST
          path: /product
          cors: true
          authorizer: ${self:custom.authorizer}

  getProducts:
    handler: src/handlers/getProducts.handler
    events:
      - http:
          method: GET
          path: /products
          cors: true
          authorizer: ${self:custom.authorizer}

  getProduct:
    handler: src/handlers/getProduct.handler
    events:
      - http:
          method: GET
          path: /product/{id}
          cors: true
          authorizer: ${self:custom.authorizer}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /product/{id}/bid
          cors: true
          authorizer: ${self:custom.authorizer}

  uploadProductPicture:
    handler: src/handlers/uploadProductPicture.handler
    events:
      - http:
          method: PATCH
          path: product/{id}/picture
          cors: true
          authorizer: ${self:custom.authorizer}

  processProducts:
    handler: src/handlers/processProducts.handler
    events:
      - schedule: rate(1 minute)

custom:
  authorizer: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:auth-service-${self:provider.stage}-auth
  ProductsTable:
    name: !Ref ProductsTable
    arn: !GetAtt ProductsTable.Arn
  MailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
  ProductsBucket:
    name: products-bucket-sj19asxm-${self:provider.stage}
