service:
  name: products-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  environment:
    PRODUCTS_TABLE_NAME: ${self:custom.ProductsTable.name}
  iamRoleStatements:
    - ${file(iam/ProductsTableIAM.yml):ProductsTableIAM}

functions:
  createProduct:
    handler: src/handlers/createProduct.handler
    events:
      - http:
          method: POST
          path: /product

  getProducts:
    handler: src/handlers/getProducts.handler
    events:
      - http:
          method: GET
          path: /products

  getProduct:
    handler: src/handlers/getProduct.handler
    events:
      - http:
          method: GET
          path: /product/{id}

  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /product/{id}/bid
resources:
  Resources:
    ProductsTable: ${file(resources/ProductsTable.yml):ProductsTable}

custom:
  ProductsTable:
    name: !Ref ProductsTable
    arn: !GetAtt ProductsTable.Arn
  bundle:
    linting: false
